export const gameErrorMessages = {
	ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
	PLAYER_NOT_FOUND: 'PLAYER_NOT_FOUND',
	PLAYER_COUNT_LOW: 'PLAYER_COUNT_LOW',
	GAME_STARTED: 'GAME_STARTED',
	GAME_NOT_STARTED: 'GAME_NOT_STARTED',
	ROOM_FULL: 'ROOM_FULL',
	INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
	PERMISSION_DENIED: 'PERMISSION_DENIED',
	DISCONNECTED: 'DISCONNECTED'
};
